apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ivanht/minikube-argocd-local.git
    targetRevision: feat/changes2
    path: gitops/nginx/charts/
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: external-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
